name: Innovation Hub Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        
    - run: npm install
    
    # Yahan humne direct node chala diya hai, npm start ka kalesh khatam!
    - run: node index.js
    
